/*
 * This file uses the X-List pattern to define all required xcb types
 */

X(xcb_connect, xcb_connection_t*, (const char *display, int *screen))
X(xcb_disconnect, void, (xcb_connection_t *c))
X(xcb_get_setup, const xcb_setup_t*, (xcb_connection_t *c))
X(xcb_setup_roots_iterator, xcb_screen_iterator_t, (const xcb_setup_t *R))
X(xcb_generate_id, uint32_t, (xcb_connection_t *c))
X(xcb_request_check, xcb_generic_error_t*, (xcb_connection_t *c, xcb_void_cookie_t cookie))
X(xcb_flush, int, (xcb_connection_t *c))
X(xcb_create_window_checked, xcb_void_cookie_t, (xcb_connection_t *c,uint8_t depth,xcb_window_t wid,xcb_window_t parent,int16_t x,int16_t y, uint16_t width,uint16_t height,uint16_t border_width,uint16_t _class,xcb_visualid_t visual,uint32_t value_mask,const void *value_list))
X(xcb_map_window, xcb_void_cookie_t, (xcb_connection_t *c, xcb_window_t window))
X(xcb_change_property, xcb_void_cookie_t, (xcb_connection_t *c, uint8_t mode, xcb_window_t window, xcb_atom_t property, xcb_atom_t type, uint8_t format, uint32_t data_len, const void *data))
X(xcb_get_file_descriptor, int, (xcb_connection_t *c))
X(xcb_poll_for_event, xcb_generic_event_t*, (xcb_connection_t *c))
X(xcb_intern_atom, xcb_intern_atom_cookie_t, (xcb_connection_t *c, uint8_t only_if_exists, uint16_t name_len, const char *name))
X(xcb_intern_atom_reply, xcb_intern_atom_reply_t*, (xcb_connection_t *c, xcb_intern_atom_cookie_t cookie, xcb_generic_error_t **e))
X(xcb_destroy_window, xcb_void_cookie_t, (xcb_connection_t *c, xcb_window_t window))
X(xcb_poll_for_queued_event, xcb_generic_event_t*, (xcb_connection_t *c))
X(xcb_wait_for_event, xcb_generic_event_t*, (xcb_connection_t *c))
X(xcb_query_pointer, xcb_query_pointer_cookie_t, (xcb_connection_t *c, xcb_window_t window))
X(xcb_query_pointer_reply, xcb_query_pointer_reply_t*, (xcb_connection_t *c, xcb_query_pointer_cookie_t cookie, xcb_generic_error_t **e))
X(xcb_open_font, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_font_t fid, uint16_t name_len, const char *name))
X(xcb_close_font, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_font_t font))
X(xcb_create_glyph_cursor, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_cursor_t cid, xcb_font_t source_font, xcb_font_t mask_font, uint16_t source_char, uint16_t mask_char, uint16_t fore_red, uint16_t fore_green, uint16_t fore_blue, uint16_t back_red, uint16_t back_green, uint16_t back_blue))
X(xcb_free_cursor, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_cursor_t cursor))
X(xcb_grab_pointer, xcb_grab_pointer_cookie_t, (xcb_connection_t *conn, uint8_t owner_events, xcb_window_t grab_window, uint16_t event_mask, uint8_t pointer_mode, uint8_t keyboard_mode, xcb_window_t confine_to, xcb_cursor_t cursor, xcb_timestamp_t time))
X(xcb_grab_pointer_reply, xcb_grab_pointer_reply_t*, (xcb_connection_t *conn, xcb_grab_pointer_cookie_t cookie, xcb_generic_error_t **e))
X(xcb_ungrab_pointer, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_timestamp_t time))
X(xcb_map_window_checked, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_window_t window))
X(xcb_unmap_window_checked, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_window_t window))
X(xcb_change_window_attributes, xcb_void_cookie_t, (xcb_connection_t *conn, xcb_window_t window, uint32_t value_mask, const uint32_t *value_list))